# v2 adds the reverse proxy and new homepage
version: '3.7'

services:
  
  signup-db:
    image: dwwx/sql-server:2017
    environment:
      - sa_password=DockerCon!!!
    networks:
      - app-net

  signup-web:
    image: dwwx/signup-web:v2
    environment: 
      - ConnectionStrings:SignUpDb=Server=signup-db;Database=SignUp;User Id=sa;Password=DockerCon!!!
    labels:
      - "traefik.frontend.rule=PathPrefix:/app"
      - "traefik.frontend.priority=10"
    depends_on:
      - signup-db
    networks:
      - app-net

  homepage:
    image: dwwx/homepage
    labels:
      - "traefik.frontend.rule=PathPrefix:/"
      - "traefik.frontend.priority=1"
    networks:
      - app-net

  traefik:
    image: stefanscherer/traefik-windows
    command: --docker.endpoint=npipe:////./pipe/docker_engine --logLevel=DEBUG
    ports:
      - "8020:80"
      - "8080:8080"
    isolation: process # workaround for https://github.com/containous/traefik/issues/4409
    volumes:
      - .:C:/etc/traefik
      - type: npipe
        source: \\.\pipe\docker_engine
        target: \\.\pipe\docker_engine
    networks:
        - app-net

networks:
  app-net:
    external:
      name: nat